### PR TITLE
Added settings menu for adding/removing associations

### PR DESCRIPTION
**Pull request by hherman1**
You can now add and remove associations on the website.

### CODE REVIEW

**Comment by Wigguno** [comment]
I'll post it here too incase you don't check the discord: 

Here are my merged changes, lmk what you think.

https://gist.github.com/Wigguno/5b723daf075ec452eec8ac73ef141bf2

**Comment by hherman1** [comment]
looks very nice!

**Comment by hherman1** [comment]
although the settings menu does not show up if you uncheck everything

**Comment by hherman1** [comment]
should the settings show up even on pages that we dont edit? cause it doesnt atm

**Comment by hherman1** [comment]
https://gist.github.com/hherman1/86057270168a0370be8f0cfcb0e9cc49

five changes:
1. settings on every page (what do you think?)
2. wont scroll when you add new associations/the settings wont go beyond the top of the screen
3. if you delete all the associations, it doesnt re-add the default ones.
4. reset button to reset all to the team secret ones
5. can press enter to add an association

**Comment by hherman1** [comment]
Ive added all your changes and mine to the pull request

**Pull request merged**
